# Generated by Django 5.1.5 on 2025-03-25 13:20

import django.core.validators
import form.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('city', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong'), ('Khulna', 'Khulna'), ('Rajshahi', 'Rajshahi'), ('Sylhet', 'Sylhet'), ('Barisal', 'Barisal'), ('Rangpur', 'Rangpur'), ('Mymensingh', 'Mymensingh')], max_length=50)),
                ('pin', models.IntegerField(help_text='Enter 6 digit pin code', validators=[form.models.validate_pin_length])),
                ('state', models.CharField(max_length=50)),
                ('mobile', models.CharField(help_text='Enter 11 digit mobile number', max_length=11, validators=[django.core.validators.RegexValidator(regex='^\\d{11}$')])),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(help_text='Password must be at least 6 characters', max_length=50)),
                ('confirm_password', models.CharField(help_text='Password and confirm password should match', max_length=50)),
                ('profile_image', models.ImageField(blank=True, upload_to='pics')),
                ('my_file', models.FileField(blank=True, upload_to='attachments')),
                ('job_city', models.ManyToManyField(help_text='Select job cities', to='form.jobcity')),
            ],
        ),
    ]
