# Generated by Django 5.2 on 2025-06-03 07:24

import create_form.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('city', models.CharField(max_length=60)),
                ('area_code', models.PositiveIntegerField(help_text='Enter 4 digit area code', validators=[create_form.models.validate_area_code])),
                ('state', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong'), ('Khulna', 'Khulna'), ('Rajshahi', 'Rajshahi'), ('Sylhet', 'Sylhet'), ('Barisal', 'Barisal'), ('Rangpur', 'Rangpur'), ('Mymensingh', 'Mymensingh')], max_length=20)),
                ('mobile', models.CharField(help_text='Enter 11 digit mobile number', max_length=11, validators=[django.core.validators.RegexValidator(code='invalid_mobile', message='Mobile number must be 11 digits long.', regex='^\\d{11}$')])),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(help_text='Enter a strong password', max_length=20)),
                ('confirm_password', models.CharField(help_text='Re-enter the password for confirmation', max_length=20)),
                ('profile_image', models.ImageField(blank=True, upload_to='pics')),
                ('my_file', models.FileField(blank=True, upload_to='attachments')),
                ('job_city', models.ManyToManyField(help_text='Select job cities ', to='create_form.jobcity')),
            ],
        ),
    ]
